name: docs_pages_workflow
 
# execute this workflow automatically when a we push to main
on:
  pull_request:
    branches: [ "main" ]
jobs:
 
  build_docs_job:
    runs-on: ubuntu-latest
    container: debian:buster-slim
 
    steps:
    
    - name:  🗑 Delete deployment
      uses: strumwolf/delete-deployment-environment@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        environment: github-pages
        onlyRemoveDeployments: true
        
    - name: Prereqs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        apt-get update
        apt-get install -y git
        git clone "https://token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" .
      shell: bash
 
    - name: Execute script to build our documentation and update pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run:  |
        chmod +x docs/docs_page.sh
        "docs/docs_page.sh"
      shell: bash
